const lyrics = [
    { time: 5, text: "Yes," },
    { time: 5.5, text: "I" },
    { time: 6, text: "look" },
    { time: 6.5, text: "happy," },
    { time: 7, text: "happy" },
    { time: 7.5, text: "all" },
    { time: 8, text: "the" },
    { time: 8.5, text: "time" },
    { time: 8.5, text: "But" },
    { time: 9, text: "you" },
    { time: 9.5, text: "don't" },
    { time: 10, text: "see" },
    { time: 10.5, text: "me," },
    { time: 11, text: "see" },
    { time: 11.5, text: "me" },
    { time: 12, text: "when" },
    { time: 12.5, text: "I" },
    { time: 13, text: "cry." },
    { time: 13.5, text: "I" },
    { time: 14, text: "can't" },
    { time: 14.5, text: "find" },
    { time: 15, text: "an" },
    { time: 15.5, text: "open" },
    { time: 16, text: "door." },
    { time: 18, text: "When" },
    { time: 18.5, text: "I" },
    { time: 19, text: "try," },
    { time: 19.5, text: "it" },
    { time: 20, text: "breaks" },
    { time: 20.5, text: "me" },
    { time: 21, text: "more" },
    { time: 21.5, text: "Should" },
    { time: 22, text: "I" },
    { time: 22.5, text: "quit" },
    { time: 23, text: "and" },
    { time: 23.5, text: "should" },
    { time: 24, text: "I" },
    { time: 24.5, text: "go" },
    { time: 25, text: "Should" },
    { time: 25.5, text: "I" },
    { time: 26, text: "leave" },
    { time: 26.5, text: "this" },
    { time: 27, text: "all" },
    { time: 27.5, text: "behind?" },
    { time: 28, text: "Same" },
    { time: 28.5, text: "things" },
    { time: 29, text: "happen" },
    { time: 29.5, text: "all" },
    { time: 30, text: "the" },
    { time: 30.5, text: "time" },
    { time: 31, text: "Can't" },
    { time: 31.5, text: "get" },
    { time: 32, text: "out" },
    { time: 32.5, text: "off" },
    { time: 33, text: "my" },
    { time: 33.5, text: "mind" },
    { time: 34, text: "Doing" },
    { time: 34.5, text: "things" },
    { time: 35, text: "I" },
    { time: 35.5, text: "shouldn't" },
    { time: 36, text: "do" },
    { time: 36.5, text: "If" },
    { time: 37, text: "you" },
    { time: 37.5, text: "ask" },
    { time: 38, text: "me," },
    { time: 38.5, text: "I" },
    { time: 39, text: "have" },
    { time: 39.5, text: "no" },
    { time: 40, text: "clue" },
    { time: 40.5, text: "Yes," },
    { time: 41, text: "I" },
    { time: 41.5, text: "look" },
    { time: 42, text: "happy," },
    { time: 42.5, text: "happy" },
    { time: 43, text: "all" },
    { time: 43.5, text: "the" },
    { time: 44, text: "time" },
    { time: 44.5, text: "But" },
    { time: 45, text: "you" },
    { time: 45.5, text: "don't" },
    { time: 46, text: "see" },
    { time: 46.5, text: "me," },
    { time: 47, text: "see" },
    { time: 47.5, text: "me" },
    { time: 48, text: "when" },
    { time: 48.5, text: "I" },
    { time: 49, text: "cry" },
    { time: 49.5, text: "'Cause" },
    { time: 50, text: "I'm" },
    { time: 50.5, text: "a" },
    { time: 51, text: "master," },
    { time: 51.5, text: "master" },
    { time: 52, text: "of" },
    { time: 52.5, text: "pretending" },
    { time: 53, text: "Lately" },
    { time: 53.5, text: "never" },
    { time: 54, text: "ending" },
    { time: 54.5, text: "When" },
    { time: 55, text: "does" },
    { time: 55.5, text: "this" },
    { time: 56, text: "all" },
    { time: 56.5, text: "make" },
    { time: 57, text: "any" },
    { time: 57.5, text: "sense" },
    { time: 58, text: "to" },
    { time: 58.5, text: "me?" },
    { time: 59, text: "God," },
    { time: 59.5, text: "I" },
    { time: 60, text: "know" },
    { time: 60.5, text: "you" },
    { time: 61, text: "can" },
    { time: 61.5, text: "set" },
    { time: 62, text: "me" },
    { time: 62.5, text: "free" },
    { time: 63, text: "And" },
    { time: 63.5, text: "please" },
    { time: 64, text: "open" },
    { time: 64.5, text: "a" },
    { time: 65, text: "door" },
    { time: 65.5, text: "and" },
    { time: 66, text: "again" },
    { time: 66.5, text: "restore" },
    { time: 67, text: "this" },
    { time: 67.5, text: "broken" },
    { time: 68, text: "piece" },
    { time: 68.5, text: "of" },
    { time: 69, text: "me" },
    { time: 69.5, text: "A" },
    { time: 70, text: "better" },
    { time: 70.5, text: "treasure" },
    { time: 71, text: "chest" },
    { time: 71.5, text: "that" },
    { time: 72, text: "was" },
    { time: 72.5, text: "made" },
    { time: 73, text: "for" },
    { time: 73.5, text: "more" },
    { time: 74, text: "And" },
    { time: 74.5, text: "there" },
    { time: 75, text: "is" },
    { time: 75.5, text: "purpose" },
    { time: 76, text: "behind" },
    { time: 76.5, text: "closed" },
    { time: 77, text: "doors" },
    { time: 77.5, text: "A" },
    { time: 78, text: "better" },
    { time: 78.5, text: "treasure" },
    { time: 79, text: "chest," },
    { time: 79.5, text: "that" },
    { time: 80, text: "was" },
    { time: 80.5, text: "made" },
    { time: 81, text: "for" },
    { time: 81.5, text: "more" },
    { time: 82, text: "And" },
    { time: 82.5, text: "there" },
    { time: 83, text: "is" },
    { time: 83.5, text: "purpose" },
    { time: 84, text: "behind" },
    { time: 84.5, text: "closed" },
    { time: 85, text: "doors" },
    { time: 85.5, text: "When" },
    { time: 86, text: "does" },
    { time: 86.5, text: "this" },
    { time: 87, text: "all" },
    { time: 87.5, text: "make" },
    { time: 88, text: "any" },
    { time: 88.5, text: "sense" },
    { time: 89, text: "to" },
    { time: 89.5, text: "me?" },
    { time: 90, text: "God," },
    { time: 90.5, text: "I" },
    { time: 91, text: "know" },
    { time: 91.5, text: "you" },
    { time: 92, text: "can" },
    { time: 92.5, text: "set" },
    { time: 93, text: "me" },
    { time: 93.5, text: "free" },
    { time: 94, text: "And" },
    { time: 94.5, text: "please" },
    { time: 95, text: "open" },
    { time: 95.5, text: "a" },
    { time: 96, text: "door" },
    { time: 96.5, text: "and" },
    { time: 97, text: "again" },
    { time: 97.5, text: "restore" },
    { time: 98, text: "this" },
    { time: 98.5, text: "broken" },
    { time: 99, text: "piece" },
    { time: 99.5, text: "of" },
    { time: 100, text: "me" },
];

const lyricsContainer = document.getElementById('lyrics');
const audio = document.getElementById('audio');
let currentIndex = 0; // Track the current index of the lyrics

const typeWriter = (text, i, callback) => {
    if (i < text.length) {
        lyricsContainer.innerHTML += text.charAt(i);
        i++;
        setTimeout(() => typeWriter(text, i, callback), 50); // Typing speed
    } else {
        callback();
    }
};

const displayLyrics = () => {
    if (currentIndex < lyrics.length) {
        const { time, text } = lyrics[currentIndex];
        if (audio.currentTime >= time) {
            typeWriter(text + ' ', 0, () => {
                currentIndex++; // Move to the next lyric
                setTimeout(displayLyrics, 500); // Delay before displaying the next lyric
            });
        } else {
            requestAnimationFrame(displayLyrics); // Continue checking the time
        }
    }
};

audio.addEventListener('play', () => {
    currentIndex = 0; // Reset index when audio plays
    displayLyrics(); // Start displaying lyrics
});
